const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.resolve(__dirname, '..');
const app = fs.readFileSync(path.join(root, 'packages/client/public/app.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'packages/server/src/index.js'), 'utf8');
const session = fs.readFileSync(path.join(root, 'packages/server/src/session.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'packages/client/public/style.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'packages/client/public/index.html'), 'utf8');

function assertIncludes(haystack, needle, message) {
  assert.ok(haystack.includes(needle), message || `Expected ${needle}`);
}
function assertNotIncludes(haystack, needle, message) {
  assert.ok(!haystack.includes(needle), message || `Did not expect ${needle}`);
}

assertIncludes(app, 'const TERM_SNAPSHOT_PREFIX', 'terminal contents must be cached client-side for reload');
assertIncludes(app, 'function terminalSnapshot', 'terminal buffer must be captured before reload');
assertIncludes(app, 'entry.serialize?.serialize', 'reload snapshot must preserve ANSI SGR/colors via xterm serialize addon');
assertIncludes(app, 'const TERM_SNAPSHOT_MAX_LINES = 20000;', 'reload snapshot must keep much deeper scrollback');
assertIncludes(app, 'const TERM_SNAPSHOT_MAX_CHARS = 1024 * 1024;', 'reload snapshot must allow about 1 MiB per pane');
assertIncludes(app, 'entry.serialize?.serialize({ scrollback: TERM_SNAPSHOT_MAX_LINES })', 'serialize addon must capture configured scrollback, not just viewport rows');
assertIncludes(app, 'text = text.slice(-Math.floor(text.length * 0.6))', 'snapshot save must degrade gracefully when localStorage quota is full');
assertIncludes(app, 'buffer.viewportY', 'reload snapshot must capture the visible viewport, not scrollback tail');
assertIncludes(app, 'function hasTerminalSnapshot', 'server replay marker must be skipped when a client snapshot exists');
assertIncludes(app, 'restoreTerminalSnapshot(id, term)', 'snapshot must restore after the pane is fitted');
assertIncludes(app, 'function restoreTerminalSnapshot', 'terminal buffer must be restored after reload');
assertIncludes(app, 'window.addEventListener(\'beforeunload\', saveAllTerminalSnapshots)', 'terminal snapshots must save on reload');
assertIncludes(app, "includes('output replay disabled')", 'server reconnect marker must not overwrite restored terminal contents');
assertIncludes(app, 'writeTerminalOutput(term, msg.data, () => scheduleTerminalSnapshot(id))', 'live output must refresh terminal snapshots');
assertIncludes(app, 'const LAYOUT_SLOTS', 'layouts must declare exact visible slot counts');
assertIncludes(app, 'function visiblePaneIds', 'layouts must hide panes beyond slot capacity');
assertIncludes(app, 'function applyLayoutVisibility', 'layout visibility must be applied after selection/order changes');
assertIncludes(css, '.term-panel.layout-hidden', 'hidden overflow panes must not consume grid slots');
assertIncludes(css, 'grid-column: 1 / -1', 'empty state must span all layout columns');
assertIncludes(css, 'grid-row: 1 / -1', 'empty state must span all layout rows');
assertIncludes(app, 'requestAnimationFrame(fitAll);', 'newly visible hidden panes must be refit after selection');
assertIncludes(app, 'function customTitle', 'pane names must prefer editable custom titles');
assertIncludes(app, 'function savePanePrefs', 'pane names/order must persist without backend restart');
assertIncludes(app, 'function movePanelBefore', 'drag-sort must reorder panes');
assertIncludes(app, 'dragstart', 'panes must be draggable');
assertIncludes(app, 'drop', 'panes must accept drops');
assertIncludes(app, 'contenteditable="true"', 'pane title must be editable inline');
assertIncludes(app, 'aria-label="Fenstername"', 'editable title needs an accessible label');
assertNotIncludes(app, '<span class="term-id">', 'session codename/id must not render in pane header');
assertNotIncludes(app, 'title="focus"', 'focus pane button must be removed');
assertNotIncludes(app, 'title="half"', 'half pane button must be removed');
assertIncludes(app, 'title="Schließen" aria-label="Schließen">×</button>', 'close X must remain and be labeled');
assertIncludes(app, 'class="minimize"', 'minimize button must exist in pane header');
assertIncludes(app, 'document.addEventListener(\'paste\', handleTerminalPaste, true)', 'Ctrl+V must route paste events into active terminal before xterm/browser handlers');
assertIncludes(app, 'document.addEventListener(\'keydown\', letBrowserOwnTerminalPasteShortcut, true)', 'Ctrl+V keydown must bypass xterm raw ^V handling');
assertIncludes(app, 'e.stopImmediatePropagation();', 'Ctrl+V must stop xterm from consuming browser paste shortcut');
assertIncludes(app, 'function shouldLetBrowserHandlePaste', 'normal editable fields must keep browser paste behavior');
assertIncludes(app, "el.closest('.terminal, .xterm')", 'xterm hidden textarea must paste through PTY bridge');
assertIncludes(app, "e.clipboardData?.getData('text/plain')", 'plain text clipboard must paste into active terminal');
assertIncludes(app, 'function handleTerminalContextMenu', 'terminal right-click must emulate PowerShell copy/paste behavior');
assertIncludes(app, 'termEl.addEventListener(\'contextmenu\', e => handleTerminalContextMenu(e, id))', 'xterm panes must bind right-click copy/paste handler');
assertIncludes(app, 'entry?.term?.getSelection?.()', 'right-click with terminal selection must copy selected text');
assertIncludes(app, 'navigator.clipboard?.writeText', 'right-click copy should use Clipboard API when available');
assertIncludes(app, 'document.execCommand(\'copy\')', 'right-click copy needs fallback for insecure/non-Clipboard contexts');
assertIncludes(app, 'navigator.clipboard?.readText', 'right-click with no selection must paste clipboard text');
assertIncludes(app, 'function bracketedPastePayload', 'right-click/Ctrl+V text paste must use bracketed paste, not raw Enter/newline input');
assertIncludes(app, "return `\\x1b[200~${String(text || '').replace(/\\x1b/g, '')}\\x1b[201~`;", 'bracketed paste wrapper must preserve text insertion without submitting');
assertIncludes(app, 'function insertIntoTerminalEntry', 'safe paste helper must insert at cursor via bracketed paste');
assertIncludes(app, 'function pasteClipboardIntoTerminalEntry', 'right-click with no selection must paste text or image clipboard data');
assertIncludes(app, 'const imageFile = await readImageFileFromSystemClipboard();', 'right-click paste must check image clipboard data first');
assertIncludes(app, 'const upload = await uploadFile(imageFile, { keepBusy: true });', 'right-click image paste must upload without auto-pasting via active-pane helper');
assertIncludes(app, 'return upload ? insertIntoTerminalEntry(entry, `${upload.path} `) : false;', 'right-click image paste must insert uploaded path at clicked cursor without submitting');
assertIncludes(app, 'return insertIntoTerminalEntry(entry, await readTextFromClipboard())', 'right-click text paste must insert at clicked cursor without submitting');
assertIncludes(app, 'function findImageFileFromClipboardData', 'image paste must inspect clipboardData.files and items before text fallback');
assertIncludes(app, 'data?.files', 'browser image pastes exposed as clipboardData.files must upload');
assertIncludes(app, 'function readImageFileFromSystemClipboard', 'Ctrl+V image fallback must try navigator.clipboard.read when paste event only exposes a link');
assertIncludes(app, 'function imageUrlFromClipboardData', 'image URL/html paste must be detected before posting raw link');
assertIncludes(app, 'function uploadImageUrl', 'image links from clipboard should be fetched/uploaded when possible');
assertIncludes(app, 'e.stopImmediatePropagation();', 'handled paste must not also reach xterm and duplicate text');
assertIncludes(app, 'uploadFile(file, { pasteIntoTerminal: true });', 'Ctrl+V image/file paste and explicit file upload must route upload into active terminal');
assertIncludes(app, 'uploadFile(file, { pasteIntoTerminal: true, keepBusy: true });', 'explicit clipboard button must still route upload into active terminal');
assertIncludes(app, 'function formatUploadInsertion', 'uploads must format pasted local paths for the active terminal');
assertIncludes(app, "return `\\x01${upload.path} `;", 'uploads must paste explicit local paths into terminal instead of Hermes-specific slash commands');
assertNotIncludes(app, "return `/image ${upload.path}\\r`;", 'uploads must not use Hermes-specific /image command injection');
assertNotIncludes(app, "return `\\x1b[200~${upload.path}\\x1b[201~`;", 'uploads must not use custom Hermes composer placeholder injection');
assertNotIncludes(app, 'function isHermesSession', 'no dead Hermes-only upload branch should remain');
assertIncludes(app, 'function sanitizeTerminalInput', 'terminal-generated replies must be filtered before reaching PTY');
assertIncludes(app, 'sanitizeTerminalInput(data)', 'xterm onData must sanitize CPR/OSC replies');
assertIncludes(app, 'function sanitizeTerminalOutput', 'terminal replay output must be sanitized client-side');
assertIncludes(app, 'writeTerminalReplay(term, msg.data)', 'reload replay must use plain reset-safe writer');
assertIncludes(app, 'normalizeReplayText(data)', 'reload replay must strip raw terminal controls');
assertIncludes(app, "includes('output replay disabled')", 'server replay-disabled marker must never be printed into terminal contents');
assertIncludes(app, "msg.type === 'replay'", 'client must handle server replay messages separately from live output');
assertIncludes(app, 'writeTerminalOutput(term, msg.data, () => scheduleTerminalSnapshot(id))', 'live output must go through chunked/sanitized writer and snapshot refresh');
assertIncludes(app, 'sanitizeTerminalOutput(data)', 'replayed output must strip old leaked RGB/CPR junk');
assertIncludes(server, "type: 'replay'", 'server must send reload snapshots as replay messages, not raw output');
assertIncludes(server, "output replay disabled", 'server must not replay old pane output on browser reload');
assertNotIncludes(server, 'session.replaySnapshot()', 'server must not replay old snapshots on reload');
assertIncludes(session, 'stripAnsiForReplay', 'server replay sanitizer kept for future safe snapshots');
assertIncludes(session, 'plain snapshot', 'reload snapshot sanitizer must be explicitly plain text');
assertIncludes(app, 'OSC color reports', 'RGB color-query replies must be documented/filtered');
assertIncludes(app, 'CSI cursor reports', 'CPR cursor reports must be documented/filtered');
assertIncludes(app, 'bare leaked OSC color report fragments', 'old visible rgb junk must be documented/filtered');
assertIncludes(app, 'semicolons/ESC stripped to 101110...3R', 'binary-looking 10/11/3R leak must be documented/filtered');
assertIncludes(app, 'sanitizeTerminalInput(data)', 'stripped terminal replies must be filtered before PTY');
assertIncludes(app, 'writeTerminalOutput(term, msg.data, () => scheduleTerminalSnapshot(id))', 'stripped terminal replies must be filtered on live output');
assertIncludes(app, 'function startPointerDrag', 'pane drag must use pointer events, not depend on fragile browser native DnD');
assertIncludes(app, "dragHandle.addEventListener('pointerdown'", 'drag handle must be directly grabbable by pointerdown');
assertIncludes(app, 'function markDropTargetAt', 'pointer drag must calculate target by viewport coordinates');
assertIncludes(app, 'nearestDropPanel', 'pointer drag must work even when not exactly over a child element');
assertIncludes(app, 'Fenster verschieben', 'drag handle label must explain move behavior');
assertIncludes(app, '>✥</span>', 'drag handle icon must not be confusing dot grip');
assertIncludes(app, 'el.dataset.paneId = id;', 'pane element must expose stable id for drag/drop diagnostics');
assertIncludes(app, 'class="term-drag-handle"', 'pane header needs a free drag handle separate from editable title and X');
assertNotIncludes(app, 'drop-before', 'drag target must not split panes into before/after zones');
assertNotIncludes(app, 'drop-after', 'drag target must not split panes into before/after zones');
assertIncludes(app, 'function placeDropPlaceholder', 'drop preview must be positioned as one full-shell overlay');
assertIncludes(app, "ph.querySelector('span').textContent = 'Hier tauschen';", 'drop preview must show a single swap target');
assertIncludes(app, 'function swapPanels', 'dragging over a shell must swap with that shell');
assertIncludes(app, 'swapPanels(sourceId, targetId)', 'pointer drop must swap, not insert before/after');
assertIncludes(app, 'function dropPlaceholder', 'drag reorder must show a full slot placeholder, not only a thin line');
assertIncludes(app, 'id = \'dropPlaceholder\'', 'drag reorder must insert a visible target slot');
assertIncludes(app, 'return new Set(ids.slice(0, cap));', 'layout visibility must preserve pane order instead of prioritizing active pane');
assertIncludes(app, 'for (const id of state.order) {\n    const entry = state.sessions.get(id);', 'layout application must use persisted pane order');
assertIncludes(app, '[state.order[activeIndex], state.order[restoreIndex]]', 'restore-over-active swaps must persist logical order');
assertIncludes(app, 'function layoutSize', 'auto grid must derive rows/columns from visible pane count');
assertIncludes(app, "const LAYOUTS = ['auto', '1x1', '2x1', '3x1', '1x2', '1x3', '2x2'];", 'manual grid buttons must be reduced to auto/orientation presets');
assertIncludes(app, 'if (rows > cols) cols = Math.max(cols, Math.ceil(count / rows));', 'vertical presets keep row count and grow columns: 3x1 -> 3x2');
assertIncludes(app, 'else if (cols > rows) rows = Math.max(rows, Math.ceil(count / cols));', 'horizontal presets keep column count and grow rows: 1x3 -> 2x3');
assertIncludes(app, 'const replaceId = null;', 'new launch must grow layout instead of replacing active pane');
assertIncludes(app, 'function movePanel', 'drag reorder must support logical before/after placement');
assertIncludes(app, 'savePanePrefs();', 'reordered windows must persist across reload');

assertIncludes(css, '.term-panel.dragging', 'dragging visual state required');
assertIncludes(css, 'body.pane-dragging', 'whole page must show grabbing cursor during pointer drag');
assertIncludes(css, 'touch-action: none;', 'drag handle must not lose pointer gestures to browser panning/selection');
assertIncludes(css, 'flex: 0 0 28px;', 'drag handle must be large enough to grab reliably');
assertNotIncludes(css, '.term-panel.drop-before::before', 'CSS must not render before half-zones');
assertNotIncludes(css, '.term-panel.drop-after::after', 'CSS must not render after half-zones');
assertIncludes(css, '.drop-placeholder', 'drag target slot preview required');
assertIncludes(css, 'position: absolute;', 'drop placeholder must be overlay-only and not alter grid cell geometry');
assertIncludes(css, 'border: 2px dashed var(--tg-accent);', 'drop placeholder must be visually obvious');
assertIncludes(css, '.term-panel.drop-target', 'drag target pane must be highlighted');
assertIncludes(css, '.term-drag-handle', 'drag handle styling required');
assertIncludes(css, '.xterm-viewport::-webkit-scrollbar', 'terminal scrollbar must be themed');
assertIncludes(css, 'scrollbar-width: thin', 'terminal scrollbar must be thin');
assertIncludes(css, 'scrollbar-color:', 'terminal scrollbar must use dark colors');
assertIncludes(css, '.term-title[contenteditable="true"]', 'editable title styling required');
assertIncludes(css, 'height: 18px;', 'pane header must be ultra compact');
assertIncludes(css, '--tg-radius: 0;', 'shell panels must be square, not rounded');
assertIncludes(css, 'gap: 2px;', 'terminal grid must use very small gaps');
assertIncludes(css, 'padding: 1px;', 'terminal body padding must be minimal');
assertIncludes(css, 'body.chrome-hidden .topbar { display: none; }', 'chrome can be hidden for maximum shell space');
assertIncludes(css, '.chrome-peek', 'hidden chrome needs a tiny restore affordance');
assertIncludes(css, 'top: 50%;', 'hidden chrome restore button must avoid pane header close buttons');
assertIncludes(css, 'transform: translateY(-50%);', 'hidden chrome restore button should sit as side tab');
assertIncludes(css, 'writing-mode: vertical-rl;', 'hidden chrome restore button should be a narrow side tab');
assertIncludes(css, 'border: 2px solid var(--tg-accent);', 'hidden chrome restore button must be clearly visible');
assertIncludes(css, '0 0 0 3px rgba(0,0,0,.85)', 'hidden chrome restore button needs dark outline contrast');
assertIncludes(app, "e.target?.closest?.('#chromePeek')", 'close hit-layer must ignore chrome restore button clicks');
assertIncludes(app, "document.elementFromPoint(e.clientX, e.clientY)?.closest?.('#chromePeek')", 'close hit-layer must not close pane behind chrome restore button');
assertIncludes(app, 'const CHROME_PREF_KEY', 'chrome visibility must persist client-side');
assertIncludes(app, 'function toggleChrome', 'chrome hide/show feature required');
assertIncludes(app, "e.altKey && e.key === '0'", 'Alt+0 must toggle chrome visibility');
assertIncludes(html, 'addon-serialize.min.js', 'xterm serialize addon must load locally for color-safe reload snapshots');
assertIncludes(app, 'async function ensureSerializeAddon', 'serialize addon must be force-loaded before init');
assertIncludes(app, 'Function(code).call(window)', 'local serialize addon must execute with window as UMD global');
assertIncludes(html, 'id="chromeToggle"', 'topbar needs hide ui button');
assertIncludes(html, 'id="chromePeek"', 'hidden topbar needs restore button');
assertNotIncludes(html, 'PassiDeck</div>', 'topbar codename/logo text should not be visible');
assertIncludes(html, 'class="command-strip"', 'topbar must be one slim command strip');
assertIncludes(html, 'class="command-zone command-left"', 'topbar left zone required for fixed status and launch controls');
assertIncludes(html, 'class="command-zone command-center"', 'topbar center zone required for scrollable session tabs');
assertIncludes(html, 'class="command-zone command-right"', 'topbar right zone required for fixed controls');
assertNotIncludes(html, 'topbar-row-1', 'old two-row topbar must not return');
assertNotIncludes(html, 'topbar-row-2', 'old two-row topbar must not return');
assertIncludes(css, '.command-strip', 'command strip CSS required');
assertIncludes(css, 'grid-template-columns: auto minmax(140px, 1fr) auto;', 'session tabs must not push fixed right controls');
assertIncludes(css, '.command-right', 'right controls must remain grouped and fixed');
assertIncludes(css, '.command-center { overflow: hidden;', 'session tab rail must be clipped/scroll-safe');
assertIncludes(css, '.command-center::before, .command-center::after {\n  content: none;', 'session tab fade masks must not obscure buttons');
assertIncludes(css, 'overflow-x: auto;', 'session tabs should remain reachable by horizontal scroll');
assertNotIncludes(app, '<span>${idx + 1}</span><span class="switcher-title">', 'session tabs must not show leading numbers');
assertIncludes(app, 'btn.innerHTML = `<span class="switcher-title">', 'session tabs should show shell name only');
assertNotIncludes(html, 'hotkey-chip', 'visible Alt hotkey hint should not take topbar space');
assertNotIncludes(html, 'Alt 1–9', 'visible Alt hotkey hint should be hidden');
assertNotIncludes(css, '.hotkey-chip', 'unused hotkey chip styling should be removed');
assertIncludes(html, '⚙ settings', 'settings button must be clearly labeled');
assertIncludes(html, '⇧ upload', 'upload button must remain and be clearly labeled');
assertIncludes(html, '▧ clip img', 'clipboard image button must remain and be clearly labeled');

/* Grid Picker */
assertIncludes(html, 'id="gridPickerInline"', 'inline grid picker container required in topbar');
assertIncludes(app, 'function buildGridPicker', 'grid picker must build visual layout options');
assertIncludes(app, 'function gridSvg', 'grid picker must generate SVG grid icons');
assertIncludes(app, 'function layoutTitle', 'grid picker must explain auto-growth behavior');
assertIncludes(html, 'id="saveState"', 'topbar must show UI state sync status');
assertIncludes(html, 'id="toast" class="toast" role="status" aria-live="polite"', 'non-blocking toast status required');
assertIncludes(app, 'function showToast', 'toast helper required instead of alert');
assertNotIncludes(app, 'alert(`Upload failed:', 'upload errors must not use blocking alert');

/* Font Size */
assertIncludes(html, 'id="fontSizeSlider"', 'font size slider required in settings');
assertIncludes(html, 'id="fontSizeLabel"', 'font size label required');
assertIncludes(app, 'function setFontSize', 'font size setter must apply to all terminals');
assertIncludes(app, 'FONT_SIZE_KEY', 'font size must persist in localStorage');
assertIncludes(html, '<option value="emerald">Emerald</option>', 'new cyber emerald theme option required');
assertIncludes(html, '<option value="cyan">Cyan</option>', 'new cyber cyan theme option required');
assertIncludes(app, 'emerald:{ background:', 'xterm emerald theme required');
assertIncludes(app, 'cyan:   { background:', 'xterm cyan theme required');
assertIncludes(css, 'body[data-theme="emerald"]', 'CSS emerald theme required');
assertIncludes(css, 'body[data-theme="cyan"]', 'CSS cyan theme required');
assertIncludes(html, 'id="systemMonitorToggle"', 'system monitor must be optional from settings');
assertIncludes(html, 'id="systemMonitor"', 'optional bottom system monitor container required');
assertIncludes(html, 'data-metric="cpu"', 'system monitor must bind CPU cell for live updates');
assertIncludes(html, 'data-metric="ram"', 'system monitor must bind RAM cell for live updates');
assertIncludes(html, 'data-metric="net"', 'system monitor must bind NET cell for live updates');
assertNotIncludes(html, '--v:62%', 'system monitor must not ship fake static CPU values');
assertNotIncludes(html, '--v:41%', 'system monitor must not ship fake static RAM values');
assertNotIncludes(html, '--v:28%', 'system monitor must not ship fake static NET values');
assertIncludes(server, "app.get('/api/system-metrics'", 'server must expose live system metrics endpoint');
assertIncludes(server, 'function readSystemMetrics', 'server must compute live system metrics');
assertIncludes(server, "fs.readFileSync('/proc/net/dev'", 'server must compute network throughput from /proc/net/dev');
assertIncludes(app, 'function pollSystemMonitor', 'client must poll system metrics');
assertIncludes(app, "api('GET', '/api/system-metrics')", 'client must fetch live metrics endpoint');
assertIncludes(app, 'state.systemMonitorTimer = setInterval(pollSystemMonitor, 1000);', 'system monitor must poll once per second');
assertIncludes(app, 'function stopSystemMonitorPolling', 'system monitor must stop polling when disabled');
assertIncludes(app, 'clearInterval(state.systemMonitorTimer);', 'disabling monitor must stop polling');
assertIncludes(app, 'if (enabled) startSystemMonitorPolling();', 'enabling monitor must start polling');
assertIncludes(app, 'else stopSystemMonitorPolling();', 'disabling monitor must stop polling');
assertIncludes(app, 'const SYSTEM_MONITOR_KEY', 'system monitor visibility must persist client-side');
assertIncludes(app, 'function setSystemMonitorVisible', 'system monitor toggle helper required');
assertIncludes(app, "localStorage.getItem(SYSTEM_MONITOR_KEY) === '1'", 'system monitor must default off unless user opted in');
assertIncludes(css, '.system-monitor[hidden] { display: none !important; }', 'system monitor must be hideable');

/* Minimize */
assertIncludes(html, '<section class="minimized-bar" id="minimizedBar" hidden>', 'minimized tab bar container required');
assertIncludes(html, '<div class="minimized-tabs" id="minimizedTabs"></div>\n  </section>', 'minimized bar section must be closed correctly');
assertIncludes(app, 'function minimizePanel', 'minimize function must hide panel and add to minimized set');
assertIncludes(app, 'function restorePanel', 'restore function must show panel and remove from minimized set');
assertIncludes(css, '.minimized-bar', 'minimized bar CSS required');
assertIncludes(css, '.minimized-tab', 'minimized tab CSS required');
assertIncludes(css, '.term-panel.minimized', 'minimized panel CSS required');

/* Close Confirmation */
assertIncludes(app, 'function isSessionExited', 'exit detection for close confirmation');
assertIncludes(app, 'function requestClosePanel', 'close must route through a single requestClosePanel helper');
assertIncludes(app, 'function installCloseHitLayer', 'close must have coordinate-based hit layer for full-grid clicks');
assertIncludes(app, 'showCloseConfirm', 'close must show confirmation modal for running sessions');
assertIncludes(html, 'id="closeModal"', 'close confirmation modal HTML required');
assertNotIncludes(app, 'installGlobalActionGuards', 'global capture guards caused close/minimize event races');
assertNotIncludes(app, "document.addEventListener('pointerdown', handler, true)", 'document pointerdown capture must not open close modal early');

console.log('ui-static ok');
