const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.resolve(__dirname, '..');
function readText(...parts) {
  return fs.readFileSync(path.join(root, ...parts), 'utf8').replace(/\r\n/g, '\n');
}
const app = readText('packages/client/public/app.js');
const server = readText('packages/server/src/index.js');
const session = readText('packages/server/src/session.js');
const css = readText('packages/client/public/style.css');
const html = readText('packages/client/public/index.html');

function assertIncludes(haystack, needle, message) {
  assert.ok(haystack.includes(needle), message || `Expected ${needle}`);
}
function assertNotIncludes(haystack, needle, message) {
  assert.ok(!haystack.includes(needle), message || `Did not expect ${needle}`);
}

assertIncludes(app, 'const TERM_SNAPSHOT_PREFIX', 'terminal contents must be cached client-side for reload');
assertIncludes(app, 'function terminalSnapshot', 'terminal buffer must be captured before reload');
assertIncludes(app, 'entry.serialize?.serialize', 'reload snapshot must preserve ANSI SGR/colors via xterm serialize addon');
assertIncludes(app, 'const TERM_SNAPSHOT_MAX_LINES = 20000;', 'reload snapshot must keep much deeper scrollback');
assertIncludes(app, 'const TERM_SNAPSHOT_MAX_CHARS = 1024 * 1024;', 'reload snapshot must allow about 1 MiB per pane');
assertIncludes(app, 'entry.serialize?.serialize({ scrollback: TERM_SNAPSHOT_MAX_LINES })', 'serialize addon must capture configured scrollback, not just viewport rows');
assertIncludes(app, 'text = text.slice(-Math.floor(text.length * 0.6))', 'snapshot save must degrade gracefully when localStorage quota is full');
assertIncludes(app, 'buffer.viewportY', 'reload snapshot must capture the visible viewport, not scrollback tail');
assertIncludes(app, 'function hasTerminalSnapshot', 'server replay marker must be skipped when a client snapshot exists');
assertIncludes(app, 'restoreTerminalSnapshot(id, term)', 'snapshot must restore after the pane is fitted');
assertIncludes(app, 'function restoreTerminalSnapshot', 'terminal buffer must be restored after reload');
assertIncludes(app, 'flushUiState(); saveAllTerminalSnapshots();', 'terminal snapshots and server pane prefs must save on reload');
assertIncludes(app, "includes('output replay disabled')", 'server reconnect marker must not overwrite restored terminal contents');
assertIncludes(app, 'writeTerminalOutput(term, msg.data, () => { scheduleTerminalSnapshot(id); refreshTitleFromTerminal(id); })', 'live output must refresh terminal snapshots');
assertIncludes(app, 'function snapSuggestionsAt', 'desktop drag must compute contextual edge/corner snap suggestions');
assertIncludes(app, 'function showSnapSuggestions', 'dragging near edges must render snap proposal overlays');
assertIncludes(app, 'function chooseSnapSuggestionAt', 'corner proposals must choose quarter vs half based on pointer position');
assertIncludes(app, 'function applySnapSuggestion', 'dropping on a proposal must resize/move the free window');
assertIncludes(app, 'function slotRectsForDrag', 'dragging must compute free desktop slots and occupied swap targets');
assertIncludes(app, 'function desktopGapSlotRects', 'free desktop gaps between existing windows must become snap targets');
assertIncludes(app, 'const candidates = [...desktopGapSlotRects(occupied), ...desktopGridSlotRects', 'real free gaps must be prioritized before coarse grid slots');
assertIncludes(app, 'function chooseDesktopSlotAt', 'dragging over a free slot or occupied pane center must choose the right snap/swap action');
assertIncludes(app, 'function showDesktopSlotSuggestions', 'free slots must be visible while a window is dragged');
assertIncludes(app, 'function applyFreeSlotSnap', 'hovering a free slot must snap the dragged window into that slot');
assertIncludes(app, 'function swapWindowSlots', 'hovering the center of an occupied window must swap window positions/order');
assertIncludes(app, 'function leftoverRects', 'snap must compute remaining desktop area for other windows');
assertIncludes(app, 'function applyRectsToWindows', 'snap/layout assist must resize all visible windows together');
assertIncludes(app, 'function layoutProposals', 'third window button must generate whole-desktop layout proposals');
assertIncludes(app, 'function showLayoutAssist', 'third window button hover must show layout suggestions');
assertIncludes(app, 'function makeFreeWindow', 'panes must become free absolute desktop windows');
assertIncludes(app, 'function applyFreeWindow', 'free windows must restore pixel position and size');
assertIncludes(app, 'function clampWindowPrefs', 'persisted free-window rects must be centrally clamped to the desktop viewport');
assertIncludes(app, 'const maxX = Math.max(0, desktopW - w);', 'free-window x clamp must account for actual window width, not leave panes outside the browser');
assertIncludes(app, 'const maxY = Math.max(0, desktopH - h);', 'free-window y clamp must account for actual window height, not leave panes outside the browser');
assertIncludes(app, 'clampWindowPrefs(prefs);\n  state.panePrefs.viewport = now;', 'viewport scaling must clamp restored window prefs before applying them');
assertIncludes(app, 'clampWindowPrefs(prefs);\n  saveUiState();', 'saving pane prefs must persist clamped in-bounds window rects');
assertIncludes(app, 'state.panePrefs.windows', 'free desktop window positions must persist per layout');
assertNotIncludes(app, 'state.currentSlots', 'stale fixed-slot state must stay removed from desktop mode');
assertNotIncludes(app, 'function ensureEmptySlot', 'desktop mode must not render magnetic empty grid slots');
assertNotIncludes(app, 'function renderResizeGutters', 'desktop mode must not show prebuilt grid gutters behind windows');
assertNotIncludes(app, 'function setPaneSpan', 'desktop snap must use pixel rect suggestions, not old span slots');
assertNotIncludes(app, 'function layoutSizeWithSpans', 'desktop snap must not expand fixed grids for spans');
assertNotIncludes(app, 'function snapAt', 'old one-target snap helper must stay removed');
assertNotIncludes(app, 'function markDropTargetAt', 'old magnetic drop target helper must stay removed');
assertNotIncludes(app, 'function paneSpanPlan', 'span-packing must stay removed');
assertIncludes(css, '.layout-desktop', 'desktop canvas styling required');
assertIncludes(css, '.snap-suggestions', 'snap suggestion overlay styling required');
assertIncludes(css, '.snap-choice.active', 'active snap suggestion must be visibly different');
assertIncludes(css, '.desktop-slot-suggestions', 'dragging must render free-slot suggestions away from screen edges');
assertIncludes(css, '.desktop-slot.active', 'active free slot must be visibly highlighted');
assertIncludes(css, '.term-panel.slot-swap-target', 'occupied window center swap target must be visibly highlighted');
assertIncludes(css, '.layout-assist', 'layout assist flyout styling required');
assertIncludes(css, '.layout-card', 'layout assist choices required');
assertIncludes(css, '.layout-mini', 'layout assist needs mini desktop previews');
assertIncludes(css, '.term-panel.free-window', 'free desktop window styling required');
assertIncludes(css, 'resize: none;', 'free windows must disable native resize so custom resize controls browser bounds');
assertIncludes(css, '.window-resize-handle', 'free windows must expose a controlled resize handle');
assertNotIncludes(css, '.empty-slot, .drop-placeholder', 'old magnetic slot/drop CSS must be removed, not only suppressed');
assertIncludes(app, 'function scheduleTerminalFit', 'resize-sensitive paths must use one debounced fit scheduler');
assertIncludes(app, 'cancelAnimationFrame(state.fitFrame)', 'rapid resize storms must collapse into the latest terminal fit');
assertIncludes(app, 'if (state.fitTimer) clearTimeout(state.fitTimer);', 'delayed second-pass fits must be debounced');
assertIncludes(app, 'scheduleTerminalFit();', 'newly visible hidden panes must be refit after selection');
assertIncludes(app, 'const targetRows = heightOnly && !opts.allowHeight ? oldRows : rows;', 'height-only fits must be explicitly allowed instead of accidentally blocking pane shrink');
assertIncludes(app, 'if (entry.el.classList.contains(\'layout-hidden\') || entry.el.offsetParent === null) return;', 'hidden/minimized xterms must not be resized to zero dimensions');
assertIncludes(app, 'if (changed) entry.term.resize(cols, targetRows);', 'no-op fits must not resize xterm or trigger PTY churn');
assertIncludes(app, 'entry.term.scrollToBottom?.()', 'after shrinking panes the active prompt must stay reachable at the bottom');
assertIncludes(app, 'const ro = new ResizeObserver(() => {', 'terminal container resizes must refit height through the debounced scheduler');
assertIncludes(css, '#saveState { display: inline-block; min-width: 7ch;', 'save status text must reserve width so launch buttons do not jump');
assertIncludes(html, 'app.js?v=20260622-electron-native-copy', 'wheel scroll fix must cache-bust app.js asset');
assertIncludes(html, 'style.css?v=20260622-active-session-desc', 'active session description styling must cache-bust style.css asset');
assertIncludes(app, "const closeButton = topEl?.closest?.('button.danger');", 'close hit-layer must only react to the actual close button under the pointer');
assertIncludes(app, 'if (!btn || closeButton !== btn) return;', 'close hit-layer must not let padded close rect overlap minimize/arrange buttons');
assertNotIncludes(app, 'const pad = 8;', 'close hit-layer must not use padded close hitboxes that overlap neighboring buttons');
assertIncludes(css, 'padding: 0 74px 0 3px;', 'pane header must reserve wider action-button area without increasing height');
assertIncludes(css, 'width: 72px;\n  height: 18px;', 'three action buttons should be wider while keeping 18px header height');
assertIncludes(css, 'min-width: 24px;\n  width: 24px;\n  height: 18px;', 'individual action buttons should be wider but not taller');
assertIncludes(html, 'vendor/xterm.js', 'standalone build must load local xterm asset');
assertNotIncludes(html, 'cdn.jsdelivr.net', 'standalone build must not depend on CDN assets');
assertIncludes(html, 'data-command="hermes --tui"', 'PassiDeck must expose a Hermes TUI quick-launch command');
assertIncludes(html, '>+ tui</button>', 'topbar must include a compact Hermes TUI launch chip');
assertIncludes(html, '<span class="ql-cmd">hermes --tui</span>', 'empty state must include a Hermes TUI launch field');
assertIncludes(app, 'function sessionDescription', 'pane header must compute a visible session command/cwd description');
assertIncludes(app, 'const generated = entry?.autoTitle || session?.meta?.title || session?.title;', 'pane title must use generated model/session titles');
assertIncludes(app, 'return \'No title\';', 'pane title must not fall back to Hermes 1/Hermes 2 when no generated title exists');
assertIncludes(html, 'id="activeSessionDescription"', 'topbar must show the active session description');
assertIncludes(app, "document.getElementById('activeSessionDescription')", 'active session changes must update the topbar description');
assertIncludes(app, "const text = entry ? panelTitle(entry.session) : 'No session';", 'topbar should contain only the active pane title');
assertIncludes(app, 'function applyGeneratedTitle', 'generated title changes must refresh the pane and topbar immediately');
assertIncludes(app, 'function inferHermesSessionTitle', 'Hermes TUI session picker must infer the selected saved-session title');
assertIncludes(app, 'refreshTitleFromTerminal(id)', 'terminal output must refresh inferred Hermes session titles');
assertIncludes(css, '.active-session-desc', 'active session description needs compact topbar ellipsis styling');
assertIncludes(app, 'class="term-session-desc" hidden', 'pane header keeps the old desc node hidden because title now carries the session description');
assertIncludes(app, 'setTooltip(headerEl, sessionDescription(session))', 'pane header tooltip must expose the full session description');
assertIncludes(css, '.term-session-desc', 'session description in pane header needs compact ellipsis styling');
assertIncludes(session, 'home: os.homedir()', 'session metadata must include home so cwd can be shortened in the header');
assertIncludes(server, "const UI_THEMES = new Set(['blue', 'green', 'emerald', 'cyan', 'amber', 'purple', 'red', 'mono'])", 'server ui-state must persist all frontend theme choices');
assertNotIncludes(server, "'2x2', '3x2', '2x3'", 'server ui-state must reject retired fixed-grid layouts');
assertNotIncludes(server, "(?:47|1047|1048|1049)[hl]", 'server must not strip alternate-screen TUI sequences');
assertIncludes(server, "set-option', '-g', 'status', 'off'", 'tmux status bar must stay disabled to avoid one-row pane mismatch');
assertIncludes(server, 'function tmuxSetDefaults', 'tmux defaults must be centralized');
assertIncludes(server, 'tmuxSetDefaults(name);', 'new and reattached sessions must apply tmux defaults to their session');
assertIncludes(server, 'process.env.PASSIDECK_TMUX_SOCKET', 'tmux socket selection must not depend on fragile whitespace-split args');
assertIncludes(app, 'function installTerminalTouchScroll', 'mobile touch dragging inside terminal must scroll xterm buffer');
assertIncludes(app, 'function installTerminalWheelScroll', 'mouse wheel must scroll xterm buffer even when CLI mouse reporting is active');
assertIncludes(app, 'term.attachCustomWheelEventHandler', 'xterm wheel events must be intercepted before CLI mouse handling steals them');
assertIncludes(app, 'term.scrollLines(lines);', 'touch scroll must use xterm scrollback API instead of relying only on DOM overflow');
assertIncludes(css, 'height: 100dvh;', 'mobile viewport height must use dynamic viewport units');
assertIncludes(css, 'touch-action: pan-y;', 'terminal panes must allow vertical touch scrolling');
assertIncludes(css, '-webkit-overflow-scrolling: touch;', 'mobile grid/xterm scrolling must use native inertial touch scrolling');
assertIncludes(css, '.command-strip { display: flex; flex-wrap: wrap;', 'mobile topbar must wrap controls without page-width overflow');
assertIncludes(css, 'height: 30px;', 'mobile pane header/actions must be touch-sized');
assertNotIncludes(app, 'function customTitle', 'unused title wrapper must stay removed');
assertIncludes(app, 'function savePanePrefs', 'pane names/order must persist without backend restart');
assertIncludes(app, 'minimized: [...state.minimized]', 'ui-state payload must include minimized panes');
assertIncludes(app, 'state.panePrefs.minimized = [...state.minimized].filter(id => state.sessions.has(id));', 'minimized pane ids must persist in pane prefs and prune closed sessions');
assertIncludes(app, 'function loadPanePrefs(prefs = {})', 'minimized pane ids must restore from server ui-state panePrefs');
assertIncludes(app, 'state.minimized = new Set((state.panePrefs.minimized || []).filter(id => state.sessions.has(id)))', 'reload must restore minimized set before final layout');
assertIncludes(app, "state.minimized.forEach(id => state.sessions.get(id)?.el.classList.add('minimized'));", 'reload must reapply minimized class');
assertIncludes(app, 'savePanePrefs(); flushUiState(); saveAllTerminalSnapshots();', 'beforeunload must save minimized/order state to server');
assertIncludes(server, 'minimized: []', 'server ui-state schema must allow minimized panes after restart');
assertIncludes(server, 'Array.isArray(src.minimized)', 'server must sanitize minimized pane ids');
assertIncludes(server, 'function sanitizePanePrefs', 'server must persist/sanitize pane prefs, titles, order, and window rects');
assertIncludes(server, 'Math.max(1, Math.min(365, Number(maxDays) || UPLOAD_RETENTION_DAYS))', 'upload cleanup retention must clamp unsafe maxDays values');

assertNotIncludes(app, 'function movePanelBefore', 'dead before/after drag helper must stay removed');
assertIncludes(app, "headerEl.addEventListener('pointerdown'", 'pane header empty space must be draggable via pointer events');
assertNotIncludes(app, 'dragstart', 'desktop windows must not depend on native drag/drop');
assertNotIncludes(app, "addEventListener('drop'", 'desktop windows must not magnetically drop into grid slots');
assertIncludes(app, 'contenteditable="true"', 'pane title must be editable inline');
assertIncludes(app, 'aria-label="Window name"', 'editable title needs an accessible label');
assertNotIncludes(app, '<span class="term-id">', 'session codename/id must not render in pane header');
assertNotIncludes(app, 'title="focus"', 'focus pane button must be removed');
assertNotIncludes(app, 'title="half"', 'half pane button must be removed');
assertIncludes(app, 'data-tooltip="Close" aria-label="Close">×</button>', 'close X must remain labeled with unified tooltip');
assertIncludes(app, 'function setConnectionStatus', 'pane connection dot must have a single status helper');
assertIncludes(app, 'class="connection-dot"', 'pane header must show a connection dot');
assertIncludes(app, "el.dataset.connectionStatus = 'reconnecting'", 'new panes start orange while connecting');
assertIncludes(app, "setConnectionStatus(id, 'live')", 'open websocket must mark pane green/live');
assertIncludes(app, "setConnectionStatus(id, 'offline')", 'error/exit must mark pane red/offline');
assertIncludes(app, 'class="minimize"', 'minimize button must exist in pane header');
assertIncludes(app, 'document.addEventListener(\'paste\', handleTerminalPaste, true)', 'Ctrl+V must route paste events into active terminal before xterm/browser handlers');
assertIncludes(app, 'document.addEventListener(\'keydown\', letBrowserOwnTerminalPasteShortcut, true)', 'Ctrl+V keydown must bypass xterm raw ^V handling');
assertIncludes(app, 'e.stopImmediatePropagation();', 'Ctrl+V must stop xterm from consuming browser paste shortcut');
assertIncludes(app, 'function shouldLetBrowserHandlePaste', 'normal editable fields must keep browser paste behavior');
assertIncludes(app, "el.closest('.terminal, .xterm')", 'xterm hidden textarea must paste through PTY bridge');
assertIncludes(app, "e.clipboardData?.getData('text/plain')", 'plain text clipboard must paste into active terminal');
assertIncludes(app, 'function handleTerminalContextMenu', 'terminal right-click must emulate PowerShell copy/paste behavior');
assertIncludes(app, 'termEl.addEventListener(\'contextmenu\', e => handleTerminalContextMenu(e, id))', 'xterm panes must bind right-click copy/paste handler');
assertIncludes(app, 'entry?.term?.getSelection?.()', 'right-click with terminal selection must copy selected text');
assertIncludes(app, 'window.passideckDesktop?.copyText', 'Electron right-click and shortcut copy must prefer native desktop clipboard');
assertIncludes(app, 'navigator.clipboard?.writeText', 'right-click copy should use Clipboard API when available');
assertIncludes(app, 'document.execCommand(\'copy\')', 'right-click copy needs fallback for insecure/non-Clipboard contexts');
assertIncludes(app, 'function copyActiveTerminalSelection', 'Ctrl+Shift+C must copy xterm selection, not browser DOM selection');
assertIncludes(app, 'term.onSelectionChange', 'right-click copy must remember xterm selection before TUI mouse mode clears it');
assertIncludes(app, "entry?.term?.getSelection?.() || entry?.lastSelection || ''", 'copy helpers must fall back to remembered terminal selection');
assertIncludes(app, "entry.titleSource === 'hermes-session'", 'Hermes saved-session titles must not be overwritten by later terminal OSC noise');
assertIncludes(app, 'function activeTerminalSelectionText', 'Electron wrapper must be able to read xterm selection text for native clipboard writes');
assertIncludes(app, 'window.__passideckGetSelection', 'Electron wrapper must read selected xterm text before native copy');
assertIncludes(app, 'window.__passideckClearSelection', 'Electron wrapper must clear xterm selection after native copy');
assertIncludes(app, 'window.__passideckCopySelection', 'Electron wrapper must be able to invoke xterm selection copy');
assertIncludes(app, "key !== 'c'", 'client must own Ctrl+Shift+C for terminal copy');
assertIncludes(app, 'function handleTerminalCopyShortcut', 'Ctrl+Shift+C must be handled in capture phase before xterm/TUI consumes it');
assertIncludes(app, "document.addEventListener('keydown', handleTerminalCopyShortcut, true)", 'terminal copy shortcut must use capture phase for Hermes TUI');
assertIncludes(app, 'navigator.clipboard?.readText', 'right-click with no selection must paste clipboard text');
assertIncludes(app, 'function bracketedPastePayload', 'right-click/Ctrl+V text paste must use bracketed paste, not raw Enter/newline input');
assertIncludes(app, "return `\\x1b[200~${String(text || '').replace(/\\x1b/g, '')}\\x1b[201~`;", 'bracketed paste wrapper must preserve text insertion without submitting');
assertIncludes(app, 'function insertIntoTerminalEntry', 'safe paste helper must insert at cursor via bracketed paste');
assertIncludes(app, 'function pasteClipboardIntoTerminalEntry', 'right-click with no selection must paste text or image clipboard data');
assertIncludes(app, 'const imageFile = await readImageFileFromSystemClipboard();', 'right-click paste must check image clipboard data first');
assertIncludes(app, 'const upload = await uploadFile(imageFile, { keepBusy: true });', 'right-click image paste must upload without auto-pasting via active-pane helper');
assertIncludes(app, 'return upload ? insertIntoTerminalEntry(entry, `${upload.path} `) : false;', 'right-click image paste must insert uploaded path at clicked cursor without submitting');
assertIncludes(app, 'return insertIntoTerminalEntry(entry, await readTextFromClipboard())', 'right-click text paste must insert at clicked cursor without submitting');
assertIncludes(app, 'function findImageFileFromClipboardData', 'image paste must inspect clipboardData.files and items before text fallback');
assertIncludes(app, 'data?.files', 'browser image pastes exposed as clipboardData.files must upload');
assertIncludes(app, 'function readImageFileFromSystemClipboard', 'Ctrl+V image fallback must try navigator.clipboard.read when paste event only exposes a link');
assertIncludes(app, 'function imageUrlFromClipboardData', 'image URL/html paste must be detected before posting raw link');
assertIncludes(app, 'function uploadImageUrl', 'image links from clipboard should be fetched/uploaded when possible');
assertIncludes(app, 'e.stopImmediatePropagation();', 'handled paste must not also reach xterm and duplicate text');
assertIncludes(app, 'uploadFile(file, { pasteIntoTerminal: true });', 'Ctrl+V image/file paste and explicit file upload must route upload into active terminal');
assertIncludes(app, 'uploadFile(file, { pasteIntoTerminal: true, keepBusy: true });', 'explicit clipboard button must still route upload into active terminal');
assertIncludes(app, 'function formatUploadInsertion', 'uploads must format pasted local paths for the active terminal');
assertIncludes(app, "return `\\x01${upload.path} `;", 'uploads must paste explicit local paths into terminal instead of Hermes-specific slash commands');
assertNotIncludes(app, "return `/image ${upload.path}\\r`;", 'uploads must not use Hermes-specific /image command injection');
assertNotIncludes(app, "return `\\x1b[200~${upload.path}\\x1b[201~`;", 'uploads must not use custom Hermes composer placeholder injection');
assertNotIncludes(app, 'function isHermesSession', 'no dead Hermes-only upload branch should remain');
assertIncludes(app, 'function sanitizeTerminalInput', 'terminal-generated replies must be filtered before reaching PTY');
assertIncludes(app, 'sanitizeTerminalInput(data)', 'xterm onData must sanitize CPR/OSC replies');
assertIncludes(app, 'function sanitizeTerminalOutput', 'terminal replay output must be sanitized client-side');
assertIncludes(app, 'writeTerminalReplay(term, msg.data)', 'reload replay must use plain reset-safe writer');
assertIncludes(app, 'normalizeReplayText(data)', 'reload replay must strip raw terminal controls');
assertIncludes(app, "includes('output replay disabled')", 'server replay-disabled marker must never be printed into terminal contents');
assertIncludes(app, "msg.type === 'replay'", 'client must handle server replay messages separately from live output');
assertIncludes(app, 'writeTerminalOutput(term, msg.data, () => { scheduleTerminalSnapshot(id); refreshTitleFromTerminal(id); })', 'live output must go through chunked/sanitized writer and snapshot refresh');
assertIncludes(app, 'sanitizeTerminalOutput(data)', 'replayed output must strip old leaked RGB/CPR junk');
assertIncludes(server, "type: 'replay'", 'server must send reload snapshots as replay messages, not raw output');
assertIncludes(server, "output replay disabled", 'server must not replay old pane output on browser reload');
assertNotIncludes(server, 'session.replaySnapshot()', 'server must not replay old snapshots on reload');
assertNotIncludes(session, 'stripAnsiForReplay', 'unused server replay sanitizer must stay removed');
assertNotIncludes(session, 'plain snapshot', 'server must not keep stale plain replay snapshot code');
assertIncludes(app, 'OSC color reports', 'RGB color-query replies must be documented/filtered');
assertIncludes(app, 'CSI cursor reports', 'CPR cursor reports must be documented/filtered');
assertIncludes(app, 'bare leaked OSC color report fragments', 'old visible rgb junk must be documented/filtered');
assertIncludes(app, 'semicolons/ESC stripped to 101110...3R', 'binary-looking 10/11/3R leak must be documented/filtered');
assertIncludes(app, 'sanitizeTerminalInput(data)', 'stripped terminal replies must be filtered before PTY');
assertIncludes(app, 'writeTerminalOutput(term, msg.data, () => { scheduleTerminalSnapshot(id); refreshTitleFromTerminal(id); })', 'stripped terminal replies must be filtered on live output');
assertIncludes(app, 'function startPointerDrag', 'pane drag must use pointer events, not depend on fragile browser native DnD');
assertIncludes(app, "headerEl.addEventListener('pointerdown'", 'header background must be directly grabbable by pointerdown');
assertNotIncludes(app, 'requestPointerLock', 'window drag must use the native cursor, not pointer lock');
assertNotIncludes(app, 'function pointerLockSpeed', 'native cursor drag must not scale fake movement deltas');
assertIncludes(app, 'function dragClientPoint', 'drag must read native client coordinates');
assertNotIncludes(app, 'function showDragCursor', 'native cursor drag must not render a fake cursor');
assertNotIncludes(app, 'document.exitPointerLock', 'native cursor drag must not enter pointer lock');
assertIncludes(app, 'function startWindowResize', 'free windows must use custom resize so resize cannot escape browser bounds');
assertIncludes(app, 'Math.min(gr.width - p.x, d.startW + (pt.x - d.startX))', 'resize width must clamp to desktop bounds');
assertIncludes(app, 'Math.min(gr.height - p.y, d.startH + (pt.y - d.startY))', 'resize height must clamp to desktop bounds');
assertIncludes(app, 'window-resize-handle', 'free windows must expose a controlled resize handle instead of native browser resize');
assertIncludes(app, 'function sharedResizeGroups', 'adjacent desktop windows must expose shared-border resize groups');
assertIncludes(app, 'function startSharedResize', 'shared borders must start a coordinated resize drag');
assertIncludes(app, 'function updateSharedResize', 'shared borders must resize every touching neighbor live');
assertIncludes(app, 'beforeIds', 'shared vertical/horizontal resize must track the windows before the divider');
assertIncludes(app, 'afterIds', 'shared vertical/horizontal resize must track stacked neighbors after the divider');
assertIncludes(css, '.shared-resize-handle.vertical', 'vertical shared borders need a col-resize handle');
assertIncludes(css, '.shared-resize-handle.horizontal', 'horizontal shared borders need a row-resize handle');
assertIncludes(css, '@media (pointer: coarse), (max-width: 900px)', 'tablet/coarse pointer layout must enlarge window controls');
assertIncludes(css, 'touch-action: none;', 'tablet drag/resize handles must not trigger page scrolling');
assertIncludes(app, 'function snapSuggestionsAt', 'pointer drag must calculate contextual snap proposals by viewport coordinates');
assertNotIncludes(app, 'nearestDropPanel', 'desktop drag must not seek nearest magnetic grid/pane targets');
assertIncludes(app, "e.target.closest('.term-title, .term-actions, button')", 'title/actions must be excluded from header drag');
assertNotIncludes(app, 'Fenster verschieben', 'separate move button must stay removed');
assertNotIncludes(app, '>✥</span>', 'separate move icon must stay removed');
assertIncludes(app, 'el.dataset.paneId = id;', 'pane element must expose stable id for drag/drop diagnostics');
assertNotIncludes(app, 'class="term-drag-handle"', 'pane header itself is the drag surface; no separate drag handle');
assertNotIncludes(app, 'drop-before', 'drag target must not split panes into before/after zones');
assertNotIncludes(app, 'drop-after', 'drag target must not split panes into before/after zones');
assertIncludes(app, 'function showSnapSuggestions', 'drag preview must be contextual snap choices, not slot placeholders');
assertIncludes(app, 'Top-left quarter', 'corner snap suggestions must offer quarter placement');
assertIncludes(app, 'Left half', 'edge/corner snap suggestions must offer half placement');
assertIncludes(app, 'function applySnapSuggestion', 'pointer drop must apply the selected snap proposal');
assertIncludes(app, 'class="arrange"', 'each window needs a third arrange/snap-assist button');
assertIncludes(app, "arrangeBtn.addEventListener('mouseenter'", 'arrange button must show proposals on hover');
assertNotIncludes(app, 'function visiblePaneIds', 'unused visible pane helper must stay removed');
assertIncludes(app, 'for (const id of state.order) {', 'desktop layout application must use persisted pane order');
assertIncludes(app, 'if (!state.minimized.has(id)) bringWindowToFront(id);', 'clicking a non-minimized top switcher tab must bring that desktop window to the foreground');
assertIncludes(app, 'function savePanePrefs', 'pane prefs persistence must exist');
assertIncludes(app, 'if (!state.sessions.has(id)) delete prefs[id]', 'pane prefs must prune windows for deleted sessions');
assertIncludes(app, '!state.minimized.has(id) && !el.classList.contains(\'layout-hidden\')', 'resize observer must not persist hidden/minimized geometry');
assertIncludes(app, 'function nextWindowZ', 'desktop windows need small monotonic z-index values, not timestamp values clamped by CSS');
assertIncludes(app, 'filter(v => v > 0 && v < 10000)', 'old timestamp z-index values must be migrated away');
assertNotIncludes(app, 'z: Date.now', 'window z-index must not use epoch timestamps because browsers clamp them');
assertIncludes(app, 'function freeSpaceWindowRect', 'new windows must search for free desktop space first');
assertIncludes(app, 'function desktopCandidates', 'auto placement must test standard desktop half/quarter candidates');
assertIncludes(app, 'rectOverlap', 'auto placement must avoid occupied window rectangles');
assertNotIncludes(app, 'function getCurrentSlotCount', 'desktop restore must not depend on retired fixed grid slots');
assertIncludes(app, 'function smartRestorePanel(id) {\n  restorePanel(id);\n  bringWindowToFront(id);\n}', 'minimized top tab must restore and foreground the same window');
assertIncludes(app, 'const replaceId = null;', 'new launch must create another desktop window instead of replacing active pane');
assertIncludes(app, 'autoPlace: true', 'new launch must auto-place into free space before foreground cascade');
assertNotIncludes(app, 'autoRestoreToFillSlots', 'retired fixed-grid restore helper must stay removed');
assertNotIncludes(app, 'function movePanel(', 'dead before/after drag helper must stay removed');
assertIncludes(app, 'savePanePrefs();', 'window positions must persist across reload');
assertIncludes(app, 'function defaultWindowSize()', 'drag restore must use a normal desktop window size');
assertIncludes(app, 'const restore = r.width > normal.w + 24 || r.height > normal.h + 24;', 'large windows must restore to normal size when dragged like desktop OS windows');

assertIncludes(css, '.term-panel.dragging', 'dragging visual state required');
assertIncludes(css, 'body.pane-dragging', 'whole page must show grabbing cursor during pointer drag');
assertIncludes(css, 'touch-action: none;', 'header drag surface must not lose pointer gestures to browser panning/selection');
assertIncludes(css, 'user-select: none;', 'header drag surface must not select text while dragging');
assertNotIncludes(css, '.term-panel.drop-before::before', 'CSS must not render before half-zones');
assertNotIncludes(css, '.term-panel.drop-after::after', 'CSS must not render after half-zones');
assertIncludes(css, '.snap-suggestions', 'snap suggestion overlay required');
assertIncludes(css, 'position: absolute;', 'snap suggestions must be overlay-only and not alter window geometry');
assertIncludes(css, '.snap-choice.active', 'active snap suggestion must be highlighted');
assertNotIncludes(css, '.empty-slot, .drop-placeholder', 'stale magnetic slot/drop visuals must be removed');
assertIncludes(css, '.term-panel.free-window .term-header { cursor: move; }', 'free-window header background must show move cursor');
assertIncludes(css, '.xterm-viewport::-webkit-scrollbar', 'terminal scrollbar must be themed');
assertIncludes(css, 'scrollbar-width: thin', 'terminal scrollbar must be thin');
assertIncludes(css, 'scrollbar-color:', 'terminal scrollbar must use dark colors');
assertIncludes(css, '.term-title[contenteditable="true"]', 'editable title styling required');
assertIncludes(css, '.connection-dot', 'connection dot styling required');
assertIncludes(css, 'data-connection-status="live"', 'green live status required');
assertIncludes(css, 'data-connection-status="reconnecting"', 'orange reconnecting status required');
assertIncludes(css, 'data-connection-status="offline"', 'red offline status required');
assertIncludes(css, 'height: 18px;', 'pane header must be ultra compact');
assertIncludes(css, '--tg-radius: 0;', 'shell panels must be square, not rounded');
assertIncludes(css, 'padding: 2px;', 'desktop canvas padding must stay compact');
assertIncludes(css, 'padding: 1px;', 'terminal body padding must be minimal');
assertIncludes(css, 'body.chrome-hidden .topbar { display: none; }', 'chrome can be hidden for maximum shell space');
assertIncludes(css, '.chrome-peek', 'hidden chrome needs a tiny restore affordance');
assertIncludes(css, 'top: 50%;', 'hidden chrome restore button must avoid pane header close buttons');
assertIncludes(css, 'transform: translateY(-50%);', 'hidden chrome restore button should sit as side tab');
assertIncludes(css, 'writing-mode: vertical-rl;', 'hidden chrome restore button should be a narrow side tab');
assertIncludes(css, 'border: 2px solid var(--tg-accent);', 'hidden chrome restore button must be clearly visible');
assertIncludes(css, '0 0 0 3px rgba(0,0,0,.85)', 'hidden chrome restore button needs dark outline contrast');
assertIncludes(app, "e.target?.closest?.('#chromePeek')", 'close hit-layer must ignore chrome restore button clicks');
assertIncludes(app, "topEl?.closest?.('#chromePeek')", 'close hit-layer must not close pane behind chrome restore button');
assertIncludes(app, 'chromeHidden: document.body.classList.contains', 'chrome visibility must persist server-side');
assertIncludes(app, 'function toggleChrome', 'chrome hide/show feature required');
assertIncludes(app, "e.altKey && e.key === '0'", 'Alt+0 must toggle chrome visibility');
assertIncludes(html, 'vendor/addon-serialize.js', 'xterm serialize addon must load locally for color-safe reload snapshots');
assertIncludes(app, 'async function ensureSerializeAddon', 'serialize addon must be force-loaded before init');
assertIncludes(app, 'Function(code).call(window)', 'local serialize addon must execute with window as UMD global');
assertIncludes(html, 'id="chromeToggle"', 'topbar needs hide ui button');
assertIncludes(html, 'id="chromePeek"', 'hidden topbar needs restore button');
assertNotIncludes(html, 'PassiDeck</div>', 'topbar codename/logo text should not be visible');
assertIncludes(html, 'class="command-strip"', 'topbar must be one slim command strip');
assertIncludes(html, 'class="command-zone command-left"', 'topbar left zone required for fixed status and launch controls');
assertIncludes(html, 'class="command-zone command-center"', 'topbar center zone required for active session description');
assertIncludes(html, 'class="command-zone command-right"', 'topbar right zone required for fixed controls');
assertNotIncludes(html, 'topbar-row-1', 'old two-row topbar must not return');
assertNotIncludes(html, 'topbar-row-2', 'old two-row topbar must not return');
assertIncludes(css, '.command-strip', 'command strip CSS required');
assertIncludes(css, 'grid-template-columns: auto minmax(140px, 1fr) auto;', 'session tabs must not push fixed right controls');
assertIncludes(css, '.command-right', 'right controls must remain grouped and fixed');
assertIncludes(css, '.command-center { overflow: hidden;', 'session tab rail must be clipped/scroll-safe');
assertIncludes(css, '.command-center::before, .command-center::after {\n  content: none;', 'session tab fade masks must not obscure buttons');
assertNotIncludes(app, '<span>${idx + 1}</span><span class="switcher-title">', 'session tabs must not show leading numbers');
assertIncludes(app, "root.textContent = text;", 'topbar should show active session description as plain text only');
assertNotIncludes(app, 'role="button" aria-label="Close"', 'switcher close must not be an invalid nested role-button span');
assertNotIncludes(html, 'hotkey-chip', 'visible Alt hotkey hint should not take topbar space');
assertNotIncludes(html, 'Alt 1–9', 'visible Alt hotkey hint should be hidden');
assertNotIncludes(css, '.hotkey-chip', 'unused hotkey chip styling should be removed');
assertIncludes(html, '⚙ settings', 'settings button must be clearly labeled');
assertIncludes(html, '⇧ upload', 'upload button must remain and be clearly labeled');
assertIncludes(html, '▧ clip img', 'clipboard image button must remain and be clearly labeled');

/* Desktop mode label */
assertIncludes(html, 'id="gridPickerInline"', 'desktop mode label container required in topbar');
assertIncludes(app, 'function buildGridPicker', 'desktop mode indicator must be built in the former layout control slot');
assertNotIncludes(app, 'function gridSvg', 'layout control must not use misleading grid icons');
assertNotIncludes(app, 'id="layoutSelect"', 'desktop mode must not expose fixed preset layout selection');
assertIncludes(app, 'Desktop', 'topbar should show Desktop mode instead of fixed layout presets');
assertIncludes(html, 'id="saveState"', 'topbar must show UI state sync status');
assertIncludes(html, 'id="toast" class="toast" role="status" aria-live="polite"', 'non-blocking toast status required');
assertIncludes(app, 'function showToast', 'toast helper required instead of alert');
assertNotIncludes(app, 'alert(`Upload failed:', 'upload errors must not use blocking alert');
assertIncludes(app, "const date = new Date(value);", 'codex reset formatter must parse ISO reset timestamps');
assertNotIncludes(app, 'new Date(Number(ts) * 1000)', 'codex reset formatter must not treat ISO timestamps as Unix seconds only');
assertIncludes(html, 'app.js?v=20260622-electron-native-copy', 'app.js must be cache-busted after wheel scroll fix');

/* Font Size */
assertIncludes(html, 'id="fontSizeSlider"', 'font size slider required in settings');
assertIncludes(html, 'id="fontSizeLabel"', 'font size label required');
assertIncludes(app, 'function setFontSize', 'font size setter must apply to all terminals');
assertIncludes(app, 'fontSize: state.fontSize', 'font size must persist in server ui-state');
assertIncludes(html, 'id="skinSelect"', 'settings must expose compact chrome skin selection');
assertIncludes(app, 'function setSkin', 'chrome skin setter must apply and persist visual density polish');
assertIncludes(app, 'skin: state.skin', 'chrome skin must persist in server ui-state');
assertIncludes(server, "const UI_SKINS = new Set(['neon', 'stealth', 'prism'])", 'server ui-state must persist allowed chrome skin choices');
assertIncludes(css, 'body[data-skin="neon"]', 'neon chrome skin required');
assertIncludes(css, 'body[data-skin="stealth"]', 'stealth chrome skin required');
assertIncludes(css, 'body[data-skin="prism"]', 'prism edge chrome skin required');
assertIncludes(css, 'body[data-skin="prism"] { --tg-glow-soft: color-mix(in srgb, var(--tg-accent)', 'prism skin glow must follow selected theme accent');
assertIncludes(css, 'body[data-skin="prism"] .term-panel.active::before { box-shadow: inset 0 0 0 1px var(--tg-edge-hot), inset 2px 0 0 var(--tg-accent)', 'prism active frame must use theme accent, not hardcoded cyan/purple');
assertIncludes(css, 'body {\n  --tg-panel-bg: color-mix(in srgb, var(--tg-surface) 88%, #000 12%);', 'derived chrome colors must be recomputed on body after selected theme variables');
assertIncludes(css, '--tg-edge-hot: color-mix(in srgb, var(--tg-accent) 70%, white 10%);', 'edge highlight must derive from selected theme accent');
assert(!css.includes('body[data-skin="prism"] { --tg-glow-soft: color-mix(in srgb, var(--tg-cyan)'), 'prism skin must not hardcode cyan glow over other themes');
assert(!css.includes('body[data-skin="prism"] .term-panel.active::before { box-shadow: inset 0 0 0 1px var(--tg-edge-hot), inset 2px 0 0 var(--tg-cyan)'), 'prism active frame must not hardcode cyan side border');
assertIncludes(css, '.term-panel::before', 'premium panel border overlay required without increasing header size');
assertIncludes(css, '.term-panel.active::before', 'active window frame needs refined border highlight');
assertIncludes(html, '<option value="emerald">Emerald</option>', 'new cyber emerald theme option required');
assertIncludes(html, '<option value="cyan">Cyan</option>', 'new cyber cyan theme option required');
assertIncludes(app, 'emerald:{ background:', 'xterm emerald theme required');
assertIncludes(app, 'cyan:   { background:', 'xterm cyan theme required');
assertIncludes(css, 'body[data-theme="emerald"]', 'CSS emerald theme required');
assertIncludes(css, 'body[data-theme="cyan"]', 'CSS cyan theme required');
assertIncludes(html, 'id="systemMonitorToggle"', 'system monitor must be optional from settings');
assertIncludes(html, '<section id="systemMonitor" class="system-monitor" hidden aria-label="System monitor">', 'system monitor must live in the top command strip');
assertIncludes(html, 'data-metric="cpu"', 'system monitor must bind CPU cell for live updates');
assertIncludes(html, 'data-metric="ram"', 'system monitor must bind RAM cell for live updates');
assertIncludes(html, 'data-metric="disk"', 'system monitor must bind disk cell for live updates');
assertNotIncludes(html, 'data-metric="net"', 'top monitor must not show noisy network cell');
assertNotIncludes(html, '--v:62%', 'system monitor must not ship fake static CPU values');
assertNotIncludes(html, '--v:41%', 'system monitor must not ship fake static RAM values');
assertIncludes(server, "app.get('/api/system-metrics'", 'server must expose live system metrics endpoint');
assertIncludes(server, 'function readSystemMetrics', 'server must compute live system metrics');
assertIncludes(server, 'function readDiskMetrics', 'server must compute live disk metrics');
assertIncludes(server, 'fs.statfsSync', 'disk metrics must use filesystem stats');
assertIncludes(app, 'function pollSystemMonitor', 'client must poll system metrics');
assertIncludes(app, "api('GET', '/api/system-metrics')", 'client must fetch live metrics endpoint');
assertIncludes(app, "for (const key of ['cpu', 'ram', 'disk'])", 'client monitor must update CPU, RAM, and disk');
assertIncludes(app, 'metrics.diskInfo', 'disk monitor must expose hover details from backend diskInfo');
assertIncludes(app, 'function setTooltip', 'unified tooltip setter must remove native title duplicates');
assertIncludes(app, "el.removeAttribute('title');", 'unified tooltip setter must remove native browser title tooltip duplicates');
assertIncludes(app, "label.textContent = '--%';", 'disk monitor must show unavailable state instead of false 0% when backend lacks diskInfo');
assertIncludes(css, '.app-tooltip {', 'unified app tooltip layer required');
assertIncludes(css, '--z-tooltip:', 'tooltip z-index must be centralized');
assertIncludes(css, 'z-index: var(--z-tooltip);', 'tooltip must render through centralized z-index scale');
assertNotIncludes(css, '214748', 'z-index magic numbers must stay centralized as CSS vars');
assertIncludes(app, 'function placeTooltip', 'tooltip placement must be viewport-aware');
assertIncludes(app, 'const TOOLTIP_DELAY_MS = 300;', 'hover tooltips must wait 300ms before opening');
assertIncludes(app, 'function scheduleTooltip', 'hover tooltips must be delayed instead of instant');
assertIncludes(app, 'setTimeout(() => {', 'tooltip delay must use a timer');
assertIncludes(app, 'if (target) scheduleTooltip(target);', 'pointer hover must schedule delayed tooltip display');
assertNotIncludes(app, 'if (target) placeTooltip(target);\n  }, true);\n  document.addEventListener(\'pointermove\'', 'pointer hover must not show tooltip instantly');
assertIncludes(app, 'Math.min(left, window.innerWidth - r.width - TOOLTIP_MARGIN)', 'tooltip must clamp horizontally inside viewport');
assertIncludes(app, 'tr.bottom + 8 + r.height <= window.innerHeight - TOOLTIP_MARGIN', 'tooltip must flip above when bottom would leave viewport');
assertNotIncludes(css, 'content: attr(data-tooltip)', 'old pseudo tooltips must not create duplicate hover text');
assertNotIncludes(html, ' title=', 'native title attributes must not ship in HTML');
assertIncludes(css, '.monitor-cell.unavailable b', 'unavailable disk monitor state must be styled');
assertIncludes(app, 'state.systemMonitorTimer = setInterval(pollSystemMonitor, 1000);', 'system monitor must poll once per second');
assertIncludes(app, 'function stopSystemMonitorPolling', 'system monitor must stop polling when disabled');
assertIncludes(app, 'clearInterval(state.systemMonitorTimer);', 'disabling monitor must stop polling');
assertIncludes(app, 'if (enabled) startSystemMonitorPolling();', 'enabling monitor must start polling');
assertIncludes(app, 'else stopSystemMonitorPolling();', 'disabling monitor must stop polling');
assertIncludes(app, 'systemMonitor: document.body.classList.contains', 'system monitor visibility must persist server-side');
assertIncludes(app, 'function setSystemMonitorVisible', 'system monitor toggle helper required');
assertNotIncludes(app, 'visualStableFitBurst', 'top monitor must not resize terminals when toggled');
assertIncludes(app, 'systemMonitor: document.body.classList.contains', 'system monitor must persist in server ui-state');
assertIncludes(css, '.system-monitor[hidden] { display: none !important; }', 'system monitor must be hideable');
assertIncludes(css, '--z-settings:', 'settings z-index must be centralized');
assertIncludes(css, 'z-index: var(--z-settings);', 'settings panel must stack in front of free windows via z-index var');

/* Minimize */
assertIncludes(html, '<section class="minimized-bar" id="minimizedBar" hidden>', 'legacy minimized bar container remains for compatibility');
assertIncludes(app, 'function minimizePanel', 'minimize function must hide panel and add to minimized set');
assertIncludes(app, 'function restorePanel', 'restore function must show panel and remove from minimized set');
assertIncludes(css, '.term-panel.minimized', 'minimized panel CSS required');

/* Close Confirmation */
assertNotIncludes(app, 'function isSessionExited', 'unused close helper must stay removed');
assertIncludes(app, 'function requestClosePanel', 'close must route through a single requestClosePanel helper');
assertIncludes(app, 'function installCloseHitLayer', 'close must have coordinate-based hit layer for full-grid clicks');
assertIncludes(app, 'const topEl = document.elementFromPoint(e.clientX, e.clientY);', 'close hit layer must resolve the visually topmost element first');
assertIncludes(app, "topEl?.closest?.('#termGrid .term-panel:not(.layout-hidden)')", 'close hit layer must scope hits to the visually topmost pane');
assertIncludes(app, 'btn.dataset.paneId || panel.dataset.paneId', 'close hit layer must close the pane under the visible X');
assertNotIncludes(app, "for (const btn of document.querySelectorAll('#termGrid .term-panel:not(.layout-hidden) button.danger'))", 'close hit layer must not scan buttons in DOM order because overlapped background panes can win');
assertIncludes(app, 'showCloseConfirm', 'close must show confirmation modal for running sessions');
assertIncludes(html, 'id="closeModal"', 'close confirmation modal HTML required');
assertIncludes(html, 'role="dialog" aria-modal="true" aria-labelledby="closeModalTitle"', 'close confirmation modal must expose dialog semantics');
assertNotIncludes(app, 'installGlobalActionGuards', 'global capture guards caused close/minimize event races');
assertNotIncludes(app, "document.addEventListener('pointerdown', handler, true)", 'document pointerdown capture must not open close modal early');


/* General hardening + CDP smoke coverage */
assertNotIncludes(app, 'state.order.slice(0, 9)', 'session handling must not truncate persisted sessions');
assertIncludes(app, 'const AUTH_TOKEN_KEY', 'client must support optional token-auth persistence from ?token=');
assertIncludes(app, "opts.headers['X-PassiDeck-Token'] = token", 'client API requests must send optional auth token');
assertIncludes(app, "qs.set('token', token)", 'client websocket URLs must include optional auth token');
assertIncludes(app, 'function handleCloseModalKeydown', 'close modal must trap keyboard handling');
assertIncludes(app, "e.key === 'Escape'", 'close modal must close on Escape');
assertIncludes(app, "document.getElementById('closeModalConfirm')?.focus()", 'close modal must focus close confirmation by default');
assertIncludes(app, "e.key === 'Enter'", 'close modal must confirm on Enter');
assertIncludes(app, 'closeModalReturnFocus', 'close modal must return focus to opener');
assertIncludes(server, 'const UPLOAD_MIME_ALLOWLIST = new Set', 'uploads must have an explicit MIME allowlist');
assertIncludes(server, 'function requireAllowedUploadMime', 'upload MIME allowlist must be enforced');
assertIncludes(server, 'X-Content-Type-Options', 'served uploads must send nosniff header');
assertIncludes(server, 'Content-Disposition', 'served uploads must be attachments by default');
assertIncludes(server, 'Cache-Control', 'served uploads must avoid stale public caching');
assertIncludes(server, 'PASSIDECK_AUTH_TOKEN', 'server must support optional token guard');
assertIncludes(server, 'function requestGuard', 'HTTP API must enforce origin/token guard');
assertIncludes(server, "req.path === '/health'", 'health endpoint must remain usable for readiness checks when auth token is enabled');
assertIncludes(server, 'function websocketAllowed', 'WebSocket must enforce origin/token guard');
assertIncludes(html, 'app.js?v=20260622-electron-native-copy', 'served app cache-bust must remain current for browser smoke');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
assertIncludes(pkg.scripts.test, 'tests/browser-cdp.test.js', 'npm test must include real CDP browser smoke');
assert.strictEqual(pkg.scripts['test:browser'], 'node tests/browser-cdp.test.js', 'browser smoke script should be callable directly');

console.log('ui-static ok');
